#
# Module manifest for module 'bjd.Common.Functions'
# Generated by: Brian Denicola
# Generated on: 1/2/2020
#

@{

    RootModule = 'bjd.Common.Functions.psm1'
    ModuleVersion = '1.0.23'
    GUID = 'aa94e99e-72b5-488e-9099-bf0f3859f68d'
    Author = 'Brian Denicola'
    CompanyName = 'Denicolafamily'
    Copyright = '2022'
    FunctionsToExport = '*'

}

