name: PowerShell Publish
on: [push]
jobs:
  nuget_publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Replace Name of Repository 
      run: |
        (Get-Content .\bjd.Common.Functions\bjd.Common.Functions.nuspec -Raw).Replace('bjd.Common.Functions','PSScripts') |
          Out-File .\bjd.Common.Functions\bjd.Common.Functions.nuspec
      shell: pwsh
        
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
      
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "PSScripts" -Source https://nuget.pkg.github.com/bjd145/index.json -Username bjd145 -Password ${{ secrets.MY_GITHUB_TOKEN }}
       
    - name: Nuget Pack
      run: nuget pack bjd.Common.Functions/bjd.Common.Functions.nuspec

    - name: Nuget Push
      run: nuget push *.nupkg -Source "PSScripts" -SkipDuplicate

  create_release_tag:
    runs-on: windows-latest
            
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}
        release_name: Release ${{ github.event.inputs.tag }}
        draft: false
        prerelease: false
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  create_release:
    runs-on: windows-latest
            
    steps:
    - name: Compress module
      shell: pwsh
      run: |
        Compress-Archive -Path bjd.Common.Functions -DestinationPath bjd.Common.Functions-${{ github.event.inputs.tag }}.zip
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release_tag.outputs.upload_url }}
        asset_path: bjd.Common.Functions-${{ github.event.inputs.tag }}.zip
        asset_name: bjd.Common.Functions-${{ github.event.inputs.tag }}.zip
        asset_content_type: application/zip